SET IDENTITY_INSERT [dbo].[ConverterUnitTables] ON
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (1, N'Area', N'm2', N'Square meter (m^2)', 1, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (2, N'Area', N'cm2', N'Square centimeter (cm^2)', 10000, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (3, N'Area', N'km2', N'Square kilometer (km^2)', 1E-06, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (4, N'Area', N'in2', N'Square inch (in^2)', 1550, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (5, N'Area', N'ft2', N'Square foot (ft^2)', 10.7639, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (6, N'Area', N'mi2', N'Square mile (mi^2)', 3.861E-07, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (7, N'Area', N'acre', N'Acre (acre)', 0.000247105, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (8, N'Length', N'm', N'Meter (m)', 1, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (9, N'Length', N'cm', N'Centimeter (cm)', 100, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (10, N'Length', N'km', N'Kilometer (km)', 0.001, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (11, N'Length', N'in', N'Inch (in)', 39.36996, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (12, N'Length', N'ft', N'Foot (ft)', 3.28084, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (13, N'Length', N'yd', N'Yard (yd)', 1.09361, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (14, N'Length', N'mi', N'Mile (mi)', 0.000621371, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (15, N'Mass', N'kg', N'Kilogram (kg)', 1, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (16, N'Mass', N'g', N'Gram (g)', 1000, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (17, N'Mass', N'oz', N'Ounce (oz)', 35.274, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (18, N'Mass', N'lb', N'Pound (lb)', 2.20462, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (19, N'Mass', N't', N'Ton (t)', 0.00110231, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (20, N'Time', N'day', N'Day (day)', 1, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (21, N'Time', N'hr', N'Hour (hr)', 24, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (22, N'Time', N'min', N'Minute (min)', 1440, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (23, N'Time', N'sec', N'Second (sec)', 86400, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (24, N'Time', N'wk', N'Week (wk)', 0.142857, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (25, N'Time', N'mo', N'Month (mo)', 0.0328767, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (26, N'Time', N'yr', N'Year (yr)', 0.00273973, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (27, N'Volume', N'l', N'Liter (l)', 1, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (28, N'Volume', N'ml', N'Milliter (ml)', 1000, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (29, N'Volume', N'gal', N'Gallon (gal)', 0.264172, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (30, N'Temperature', N'\u00B0C', N'Celcius', 1, 0)
INSERT INTO [dbo].[ConverterUnitTables] ([Id], [UnitType], [UnitName], [UnitLongName], [Coefficient], [Intercept]) VALUES (31, N'Temperature', N'\u00B0F', N'Farenheit', 1.8, 57.6)
SET IDENTITY_INSERT [dbo].[ConverterUnitTables] OFF
